[package]
name = "smtp-sink"
group = "infinyon"
version = "0.0.0"
apiVersion = "0.1.0"
fluvio = "0.11.9"
description = "SMTP sink connector reads records from data streaming and pushed to SMTP"
license = "MIT/Apache-2.0"
visibility = "public"

[direction]
dest = true

[deployment]
binary = "smtp-sink"